---
# need for docker build
sudo: true

addons:
  apt:
    packages:
      - realpath
      - ruby

language: go
branches:
  only:
    - master
    - csi-v1.0

go: 1.11.x

env:
  global:
    - GO_METALINTER_VERSION="v3.0.0"
    - TEST_COVERAGE=stdout
    - GO_METALINTER_THREADS=1
    - GO_COVER_DIR=_output

jobs:
  include:
    - name: Linter
      install:
        - gem install mdl
        - pip install --user --upgrade pip
        - pip install --user yamllint
        # install gometalinter
        - curl -L
         "https://raw.githubusercontent.com/alecthomas/gometalinter/"${GO_METALINTER_VERSION}"/scripts/install.sh"
         | bash -s -- -b $GOPATH/bin "${GO_METALINTER_VERSION}"
      script:
        - scripts/lint-text.sh --require-all
        - scripts/lint-go.sh
        - scripts/test-go.sh

    - name: rbdplugin
      script:
        - make rbdplugin

    - name: cephfsplugin
      script:
        - make cephfsplugin

deploy:
  - provider: script
    on:  # yamllint disable-line rule:truthy
      all_branches: true
    script: ./deploy.sh
