---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clone-rbd-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: rbd-pvc
