kind: Service
apiVersion: v1
metadata:
  name: {{ include "ceph-csi-cephfs.nodeplugin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: csi-metrics
    chart: {{ include "ceph-csi-cephfs.chart" . }}
    component: {{ .Values.nodeplugin.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ include "ceph-csi-cephfs.name" . }}
    component: {{ .Values.nodeplugin.name }}
    release: {{ .Release.Name }}
  ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: 8081
    - name: grpc-metrics
      port: 8090
      protocol: TCP
      targetPort: 8091
