---
name: mod-check
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "*"
jobs:
  mod-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: mod check
        run: GOPATH=$(go env GOPATH) make mod-check
